# Generated by Django 5.0 on 2024-12-04 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timepreset',
            unique_together={('employee', 'name')},
        ),
        migrations.AlterField(
            model_name='timepreset',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_presets', to='accounts.employee'),
        ),
        migrations.RemoveField(
            model_name='timepreset',
            name='color',
        ),
    ]
